const assert = require('node:assert/strict');
const e = require('../calc-engine.js');
const close = (a,b, eps = 1e-8) => assert.ok(Math.abs(a-b)<eps, `${a} !== ${b}`);
const concrete=e.concrete({length:2,width:3,height:.1,count:1,mixClass:'A',wastePct:5});
close(concrete.volume,.6); assert.equal(concrete.bags,6);close(concrete.sand,.315);close(concrete.gravel,.63);
const concreteAA=e.concrete({length:1,width:1,height:1,count:1,mixClass:'AA',wastePct:0});assert.equal(concreteAA.bags,12);
const paint=e.paint({type:'interior',length:10,height:3,walls:4,coats:2,openings:0,wastePct:10,canLiters:4,includePrimer:true});
close(paint.liters,22);assert.equal(paint.cans,6);close(paint.primerLiters,16.5);assert.equal(paint.primerCans,5);
const paintDeduct=e.paint({type:'interior',length:10,height:3,walls:1,coats:2,openings:6,wastePct:0,canLiters:4,includePrimer:false});close(paintDeduct.liters,4);assert.equal(paintDeduct.cans,1);
const tile=e.tile({length:6,width:5,size:'60x60',allowance:.1,pcsPerBox:4,adhesiveCoverage:5,adhesiveWastePct:10,groutRate:.4});
assert.equal(tile.tiles,92);assert.equal(tile.boxes,23);assert.equal(tile.adhesiveBags,7);close(tile.groutBuyKg,12);
const nail=e.nail({type:'roofing',length:10,boards:20,spacingCm:30,nailsPerJoint:2,wastePct:10});
assert.equal(nail.joints,35); assert.equal(nail.count,253); close(nail.kg,.759); assert.equal(nail.buyKg,1);
const beam=e.steel({project:'beam',length:6,width:.3,height:.5,spacingCm:15,coverMm:40,stockLength:12,size:12,tieSize:10,layers:1,longitudinalBars:4});
assert.equal(beam.mainPieces,2);assert.equal(beam.tiePieces,6);assert.equal(beam.stirrups,41);close(beam.mainLength,24);close(beam.tieLength,60.68);
const slab=e.steel({project:'slab',length:4,width:3,height:.15,spacingCm:20,coverMm:30,stockLength:6,size:12,tieSize:10,layers:1,longitudinalBars:4});
assert.equal(slab.countLengthwise,16);assert.equal(slab.countWidthwise,21);close(slab.mainLength,16*3.94+21*2.94);
assert.throws(()=>e.steel({project:'beam',length:15,width:.3,height:.5,spacingCm:15,coverMm:40,stockLength:12,size:12,tieSize:10,layers:1,longitudinalBars:4}),/Splicing/);
assert.throws(()=>e.tile({length:0,width:5,size:'60x60',allowance:.1,pcsPerBox:4,adhesiveCoverage:5,adhesiveWastePct:10,groutRate:.4}),/positive/);
assert.throws(()=>e.paint({type:'interior',length:10,height:3,walls:1,coats:2,openings:35,wastePct:0,canLiters:4,includePrimer:false}),/Openings/);
const prices={steel:300,ties:150,cement:250,sand:800,gravel:1000,paint:900,primer:600,tile:800,adhesive:300,grout:90,nails:120,labor:700,days:3,workers:2,overheadPct:10,contingencyPct:5};
const q={steel:beam,concrete:concrete,paint:paint,tile:tile,nail:nail};
const cost=e.cost(q,prices); const manual=2*300+6*150+6*250+.315*800+.63*1000+6*900+5*600+23*800+7*300+12*90+1*120;
close(cost.materials,manual);close(cost.labor,4200);close(cost.total,(manual+4200)*1.1*1.05);
const noNails=e.cost({...q,nail:{buyKg:0}},prices);close(cost.materials-noNails.materials,120);
console.log('PASS: 16 groups — concrete mixes, paint, tiles, adhesive, nails, rebar, safety validation, complete costs.');
console.log('Reference result for concrete:',JSON.stringify(concrete));
console.log('Reference full cost:',cost.total.toFixed(2));
